### ISSUE TITLE
not restore state save

### ISSUE THREAD

**Issue by gurues** [PiotrMachowski/Home-Assistant-custom-components-Saver#12]
Hello
I have this scripts for save and restore state but fault

```
alias: Estado iniciales
sequence:
  - service: saver.save_state
    data:
      entity_id: climate.termostato_radiador_garaje
mode: single
```
```
alias: Restaurar estados iniciales
sequence:
  - service: saver.restore_state
    data:
      entity_id: climate.termostato_radiador_garaje
      restore_script:
        - service: input_text.set_value
          data_template:
            entity_id: input_text.estado_prueba
            value: '{{ attr_hvac_action }}'
mode: single
```
```
alias: Restaurar estados iniciales 2
sequence:
  - service: saver.restore_state
    data:
      entity_id: climate.termostato_radiador_garaje
      restore_script:
        - service: input_text.set_value
          data_template:
            entity_id: input_text.estado_prueba
            value: '{{ state }}'
mode: single
```

The entety estado_prueba don´t actualize

help me please

**Comment by PiotrMachowski** [comment]
I suppose that built-in scenes will be a better solution for you, have you tried this approach?
[Creating scenes on the fly](https://www.home-assistant.io/integrations/scene/#creating-scenes-on-the-fly)

**Comment by gurues** [comment]
I was just doing tests with the integration since I want some states to be restored after HA reboots but I'm doing something wrong since it doesn't work for me

**Comment by PiotrMachowski** [comment]
Try using following ones:

```yaml
alias: Restaurar estados iniciales
sequence:
  - service: saver.restore_state
    data:
      entity_id: climate.termostato_radiador_garaje
      restore_script:
        - service: input_text.set_value
          data_template:
            entity_id: input_text.estado_prueba
            value: '{{{{ attr_hvac_action }}}}'
mode: single
```

```yaml
alias: Restaurar estados iniciales 2
sequence:
  - service: saver.restore_state
    data:
      entity_id: climate.termostato_radiador_garaje
      restore_script:
        - service: input_text.set_value
          data_template:
            entity_id: input_text.estado_prueba
            value: '{{{{ state }}}}'
mode: single
```
