### ISSUE TITLE
How to restore a text string + restoring state also deletes the saved state.

### ISSUE THREAD

**Issue by SelfDestructor** [PiotrMachowski/Home-Assistant-custom-components-Saver#21]
Hi!

I've started to understand how Saver works and got it mostly working. However for my AC units they require a string and I can't figure out how to restore that.

At the moment I got the temperature to restore but I can't figure out how to get the hvac_mode to work. It can be ```off, heat, cool```. 

```
service: saver.restore_state
data:
  entity_id: climate.new_living_room_ac
  restore_script:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.new_living_room_ac
        temperature: "{{ '{{ attr_temperature | int }}'}}"
        hvac_mode: "{{ {{ attr_state | string  }}'}}"
      target:
        entity_id: climate.new_living_room_ac

```

The state stored in saver.saver:

```
entities:
  climate.new_living_room_ac:
    entity_id: climate.new_living_room_ac
    state: cool
    attributes:
      hvac_modes:
        - 'off'
        - heat
        - cool
      min_temp: 16
      max_temp: 31
      current_temperature: 23.7
      temperature: 22
      current_humidity: 56
      hvac_action: cooling
      friendly_name: New living room AC
      supported_features: 1
    last_changed: '2023-09-09T16:05:27.713246+00:00'
    last_updated: '2023-09-09T16:07:14.049819+00:00'
    context:
      id: 01H9XB50W1WKFMZGQ68BVMXEYC
      parent_id: null
      user_id: null
variables: {}
friendly_name: saver
```

I've tried to read up on templating on the docs page and HA forum posts but it's all way above my head.

Also any time I restore the saved state, it gets deleted and saver.saver becomes empty.

**Comment by PiotrMachowski** [comment]
Try this one:
```yaml
service: saver.restore_state
data:
  entity_id: climate.new_living_room_ac
  delete_after_run: false
  restore_script:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.new_living_room_ac
        temperature: "{{ '{{ attr_temperature | int }}'}}"
        hvac_mode: "{{ '{{ attr_state | string  }}'}}"
      target:
        entity_id: climate.new_living_room_ac
```

It should also keep the stored state.

**Comment by SelfDestructor** [comment]
Thank you! 

`delete_after_run: false` works perfectly and I didn't notice I was missing an apostrophe.
It doesn't get the value still but now it lets me save the automation and when running it, I get the error `expected HVACMode or one of 'off', 'heat', 'cool', 'heat_cool', 'auto', 'dry', 'fan_only' for dictionary value @ data['hvac_mode']. Got None `

**Comment by PiotrMachowski** [comment]
How about this one?
```yaml
service: saver.restore_state
data:
  entity_id: climate.new_living_room_ac
  delete_after_run: false
  restore_script:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.new_living_room_ac
        temperature: "{{ '{{ attr_temperature | int }}'}}"
        hvac_mode: "{{ '{{ state | string  }}'}}"
      target:
        entity_id: climate.new_living_room_ac
```

**Comment by SelfDestructor** [comment]
That worked! 😁 Thank you so much!

Out of curiosity, what's the difference with and without `attr_` at the beginning?

**Comment by PiotrMachowski** [comment]
`attr_` prefix is for attributes ;)

**Comment by PiotrMachowski** [comment]
@SelfDestructor I have just released a new version which makes using saved states/variables much easier:

```yaml
State: {{ saver_entity("sun.sun") }}
State attribute: {{ saver_entity("sun.sun", "azimuth") }}
Variable: {{ saver_variable("testing") }}
```
