### ISSUE TITLE
Delete variable by wildcard

### ISSUE THREAD

**Issue by PiotrMachowski** [PiotrMachowski/Home-Assistant-custom-components-Saver#30]
### Discussed in https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **tapsystem** May  4, 2024</sup>
Hello,
Before all really a great thanks for this addon, it's really usefull , specially when you need to work with varaible update in conditionnal block and bypass the scope limitation ! 

Just an idea for an update : it's will be great to have the possibility to delete variables or entites using wildcard like
```yaml
service: saver.delete_variable
  data:
    name: myVariable_*
```
this way it's possible go generate a random variable for parrallel script execution like this
```yaml
service: saver.set_variable
    metadata: {}
    data:
      name: "{{ 'myVariable_' + ((range(10000, 99999) | random)| string ) }}"
      value: "false"
```
and so get the possibility to clear all these randoms var in an automation every night
( i was deleting random var at script end, but some time with errors ... varialbes stay in database and in memory

Thanks again for this nice job ! ;) 

(Grrrr can not get my line jump nice in code section, sorry for edit spaming)</div>
