### ISSUE TITLE
Can´t store & restore light state

### ISSUE THREAD

**Issue by tomg1970** [PiotrMachowski/Home-Assistant-custom-components-Saver#32]
I am currently trying out something with the HACS saver. But I can't get a simple light to save the status (here in the example of triggering an input_boolean.test/on), then change the color and brightness, and then switch the IB off again - which should lead to the "saver" being restored?  Or am I making a mistake?

```
alias: TEST SAVER
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_boolean.test
    from: "on"
    to: "off"
    id: ib_off
  - trigger: state
    entity_id:
      - input_boolean.test
    from: "off"
    to: "on"
    id: ib_on
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - ib_on
        sequence:
          - action: saver.save_state
            metadata: {}
            data:
              entity_id: light.esz_stehlampe
      - conditions:
          - condition: trigger
            id:
              - ib_off
        sequence:
          - action: saver.restore_state
            metadata: {}
            data:
              entity_id: light.esz_stehlampe
mode: single
```
