### ISSUE TITLE
Unable to restore state using attributes

### ISSUE THREAD

**Issue by kidhasmoxy** [PiotrMachowski/Home-Assistant-custom-components-Saver#5]
Ran save state on a climate entity. I'm able to reference state via template using: 
```
{{ state_attr('saver.saver', 'entities')['climate.dyson_air'].state == 'heat' }}
```
But the following restore script doesn't work at all (using it inside of a "Choose" block in this case): 

```
service: saver.restore_state
data:
  entity_id: climate.dyson_air
  delete_after_run: false
  restore_script:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.dyson_air
        temperature: '{{ attr_temperature | float }}'
```

Error rendering data template: UndefinedError: 'attr_temperature' is undefined

Here is the entity information:
```
entities: 
climate.dyson_air:
  entity_id: climate.dyson_air
  state: heat
  attributes:
    hvac_modes:
      - cool
      - heat
    min_temp: 34
    max_temp: 99
    fan_modes:
      - focus
      - diffuse
    current_temperature: 72
    temperature: 79
    current_humidity: 53
    fan_mode: focus
    hvac_action: heating
    friendly_name: Dyson Air
    supported_features: 9
```

**Comment by PiotrMachowski** [comment]
Can you try this version?
```
service: saver.restore_state
data:
  entity_id: climate.dyson_air
  delete_after_run: false
  restore_script:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.dyson_air
        temperature: '{{ "{{ attr_temperature | float }}" }}'
```
